function getDifficulty(countryName) {
    const correspondance = {
        'Afghanistan': 2,
        'Afrique du Sud': 2,
        'Akrotiri': 2,
        'Albanie': 1,
        'Algérie': 1,
        'Allemagne': 1,
        'Andorre': 2,
        'Angola': 2,
        'Anguilla': 2,
        'Antarctique': 3,
        'Antigua-et-Barbuda': 3,
        'Antilles néerlandaises': 3,
        'Arabie saoudite': 2,
        'Arctique': 3,
        'Argentine': 1,
        'Arménie': 2,
        'Aruba': 3,
        'Ashmore and Cartier Islands': 3,
        'Atoll de Johnston': 3,
        'Atoll de Palmyra': 3,
        'Australie': 1,
        'Autriche': 1,
        'Azerbaïdjan': 2,
        'Bahamas': 2,
        'Bahreïn': 2,
        'Bangladesh': 2,
        'Barbade': 3,
        'Belgique': 1,
        'Belize': 3,
        'Bénin': 2,
        'Bermudes': 2,
        'Bhoutan': 2,
        'Biélorussie': 2,
        'Birmanie': 2,
        'Bolivie': 2,
        'Bosnie-Herzégovine': 2,
        'Botswana': 2,
        'Brésil': 1,
        'Brunei': 2,
        'Bulgarie': 1,
        'Burkina Faso': 2,
        'Burundi': 3,
        'Cambodge': 2,
        'Cameroun': 1,
        'Canada': 1,
        'Cap-Vert': 2,
        'Chili': 2,
        'Chine': 1,
        'Chypre': 1,
        'Colombie': 2,
        'Comores': 2,
        'Congo-Brazzaville': 2,
        'Congo-Kinshasa': 2,
        'Corée du Nord': 2,
        'Corée du Sud': 1,
        'Costa Rica': 2,
        'Côte d\'Ivoire': 2,
        'Croatie': 2,
        'Cuba': 2,
        'Curaçao': 2,
        'Danemark': 1,
        'Dhekelia': 2,
        'Djibouti': 2,
        'Dominique': 2,
        'Égypte': 2,
        'Émirats arabes unis': 2,
        'Équateur': 2,
        'Érythrée': 2,
        'Espagne': 1,
        'Eswatini': 3,
        'États-Unis': 1,
        'Éthiopie': 2,
        'Falkland Islands': 3,
        'Fidji': 2,
        'Finlande': 1,
        'France': 1,
        'Gabon': 2,
        'Gambie': 2,
        'Gaza Strip': 3,
        'Géorgie': 2,
        'Ghana': 2,
        'Gibraltar': 3,
        'Grèce': 1,
        'Grenade': 3,
        'Groenland': 3,
        'Guadeloupe': 2,
        'Guam': 3,
        'Guatemala': 2,
        'Guernesey': 3,
        'Guinée': 2,
        'Guinée équatoriale': 3,
        'Guinée-Bissau': 3,
        'Guyana': 2,
        'Haïti': 2,
        'Honduras': 2,
        'Hong Kong': 2,
        'Hongrie': 1,
        'Île Bouvet': 3,
        'Île Christmas': 3,
        'Île Clipperton': 3,
        'Île de Man': 3,
        'Île Europa': 3,
        'Île Heard et îles McDonald': 3,
        'Île Jan Mayen': 3,
        'Île Juan de Nova': 3,
        'Île Norfolk': 3,
        'Île Tromelin': 3,
        'Îles Ashmore et Cartier': 3,
        'Îles Caïmans': 3,
        'Îles Cocos': 3,
        'Îles Cook': 3,
        'Îles de la mer de Corail': 3,
        'Îles Féroé': 3,
        'Îles Glorieuses': 3,
        'Îles Malouines': 3,
        'Îles Mariannes du Nord': 3,
        'Îles Marshall': 3,
        'Îles Pitcairn': 3,
        'Îles Salomon': 3,
        'Îles Sandwich du Sud': 3,
        'Îles Spratly': 3,
        'Îles Turques-et-Caïques': 3,
        'Îles Vierges américaines': 3,
        'Îles Vierges britanniques': 3,
        'Inde': 1,
        'Indonésie': 2,
        'Iran': 2,
        'Iraq': 2,
        'Irlande': 2,
        'Islande': 2,
        'Israël': 2,
        'Italie': 1,
        'Jamaïque': 2,
        'Japon': 1,
        'Jersey': 2,
        'Jordanie': 2,
        'Kazakhstan': 2,
        'Kenya': 2,
        'Kirghizistan': 2,
        'Kiribati': 3,
        'Koweït': 2,
        'Laos': 2,
        'Lesotho': 2,
        'Lettonie': 1,
        'Liban': 2,
        'Libéria': 2,
        'Libye': 2,
        'Liechtenstein': 3,
        'Lituanie': 1,
        'Luxembourg': 1,
        'Macao': 3,
        'Madagascar': 2,
        'Malaisie': 2,
        'Malawi': 3,
        'Maldives': 3,
        'Mali': 2,
        'Malte': 2,
        'Maroc': 1,
        'Martinique': 2,
        'Maurice': 2,
        'Mauritanie': 2,
        'Mayotte': 2,
        'Mexique': 2,
        'Micronésie': 2,
        'Moldavie': 2,
        'Monaco': 1,
        'Mongolie': 2,
        'Monténégro': 2,
        'Montserrat': 2,
        'Mozambique': 2,
        'Namibie': 2,
        'Nauru': 2,
        'Navassa Island': 3,
        'Népal': 2,
        'Nicaragua': 3,
        'Niger': 2,
        'Nigeria': 2,
        'Nioué': 2,
        'Norvège': 1,
        'Nouvelle-Calédonie': 2,
        'Nouvelle-Zélande': 2,
        'Oman': 2,
        'Ouganda': 2,
        'Ouzbékistan': 2,
        'Pakistan': 2,
        'Palaos': 2,
        'Panama': 2,
        'Papouasie-Nouvelle-Guinée': 3,
        'Paraguay': 2,
        'Pays-Bas': 1,
        'Pérou': 2,
        'Philippines': 2,
        'Pologne': 1,
        'Polynésie française': 2,
        'Porto Rico': 2,
        'Portugal': 1,
        'Qatar': 2,
        'République centrafricaine': 2,
        'République dominicaine': 2,
        'République tchèque': 2,
        'Réunion': 2,
        'Roumanie': 1,
        'Royaume-Uni': 1,
        'Russie': 2,
        'Rwanda': 2,
        'Sahara occidental': 2,
        'Saint-Christophe-et-Niévès': 3,
        'Sainte-Hélène': 3,
        'Sainte-Lucie': 3,
        'Saint-Marin': 3,
        'Saint-Pierre-et-Miquelon': 3,
        'Saint-Vincent-et-les Grenadines': 3,
        'Salvador': 2,
        'Samoa': 3,
        'Samoa américaines': 3,
        'São Tomé-et-Príncipe': 3,
        'Sénégal': 2,
        'Serbie': 2,
        'Seychelles': 2,
        'Sierra Leone': 3,
        'Singapour': 2,
        'Slovaquie': 2,
        'Slovénie': 2,
        'Somalie': 2,
        'Soudan': 2,
        'Soudan du Sud': 2,
        'Sri Lanka': 2,
        'Suède': 1,
        'Suisse': 1,
        'Suriname': 3,
        'Svalbard': 3,
        'Syrie': 2,
        'Tadjikistan': 2,
        'Taïwan': 2,
        'Tanzanie': 3,
        'Tchad': 2,
        'Terres australes et antarctiques françaises': 3,
        'Territoire britannique de l\'océan Indien': 3,
        'Territoire des îles Cocos (Keeling)': 3,
        'Thaïlande': 2,
        'Timor oriental': 2,
        'Togo': 2,
        'Tokelau': 3,
        'Tonga': 2,
        'Trinité-et-Tobago': 2,
        'Tunisie': 1,
        'Turkménistan': 2,
        'Turquie': 2,
        'Tuvalu': 3,
        'Ukraine': 2,
        'Uruguay': 2,
        'Vanuatu': 2,
        'Vatican': 3,
        'Venezuela': 2,
        'Viêt Nam': 2,
        'Wallis-et-Futuna': 3,
        'Yémen': 2,
        'Zambie': 2,
        'Zimbabwe': 2,
    };

    const normalizedCountryName = countryName.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f\s'-]/g, "");

    for (let pays in correspondance) {
        const normalizedPays = pays.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f\s'-]/g, "");

        if (normalizedPays === normalizedCountryName) {
            return correspondance[pays];
        }
    }
}
